admin.approveUser_server.php
admin.copyGenome_server.php
admin.copyHapmap_server.php
admin.copyProject_server.php
admin.copyProjectToAdmin_server.php
admin.deleteGenome_server.php
admin.deleteProject_server.php
admin.deleteUser_server.php
admin.error_server.php
admin.error_window.php
admin.lockUserProject_server.php
admin.lockUser_server.php
admin.minimizeProject_server.php
admin.unlockUserProject_server.php
genome.create_server.php
genome.create_window2.php
genome.create_window.php
genome.delete_server.php
genome.working.php
genome.working_server.php
hapmap.addTo.php
hapmap.addTo_window.php
hapmap.create_window.php
hapmap.delete_server.php
hapmap.finalize_hapmap.php
hapmap.working.php
hapmap.working_server.php
images.combine.php
index.php
panel.admin1.php
panel.admin2.php
panel.admin3.php
panel.citations.php
panel.genome.php
panel.hapmap.php
panel.help.php
panel.manageDataset.php
panel.super1.php
panel.super2.php
panel.user.php
panel.visualizeDataset.php
project.admin_working.php
project.admin_working_server.php
project_bulk.create_server.php
project_bulk.create_window.php
project.create_server.php
project.create_window.php
project.delete_server.php
project.minimize_server.php
project.update_server.php
project.update_window.php
project.working.php
project.working_server.php
run_bulk_processer.php
uploader.1.php
uploader.2.php
upload_processer.php
user.delete.php
user.delete_server.php
