#!/usr/bin/env Rscript
args = commandArgs(trailingOnly=TRUE)
# $base_name1		: seq 1 name.
# $tempdir/results1.txt	: results 1 name.
# $kmer_size		: size of subset to use for identity examination.
# $tempdir/$3		: output file name.

# args[1] = FASTA sequence file to be analyzed.
# args[2] = intermediate output.txt file location, generated by "repetitiveness.make_plot.py".
# args[3] = kmer length;
# args[4] = final PNG figure name;
# args[5] = source FASTA file name.
# args[6] = plot color;

kmer_length = strtoi(args[3]);

# test if there is at least one argument: if not, return an error
if (length(args)<5) {
	stop("At least five arguments must be supplied (input file).n", call.=FALSE)
}

# load raw data.
data1  <- read.csv(args[2]);
ydata1 <- unlist(data1[2],use.names=FALSE);
xdata1 <- rep(1:nrow(data1));

# scale ydata
#ydata1 = ydata1/(kmer_length);

# Find max values.
minY   = min(ydata1);
maxY   = max(ydata1);
maxX   = max(xdata1);

# Set maxX to maximum length of DA2 assembly chromosomes, so full chromosome repetitiveness plots will be comparable.
maxX   = 3221506;

# make plot, save to PNG.
png(filename=args[4], width=2400, height=400);

plot(xdata1,ydata1, xlim=c(0,maxX), ylim=c(-0.6,0.6), ylab="GC skew", xlab="bp", pch=19, col=args[6], cex=0.03125);
mtext(paste("GC-skew ( k =",as.character(kmer_length),") of"),side=3,line=1);
mtext(args[5],side=3,line=0);
